Legoas_Test/Models/Layar.cs
using System;
using System.Collections.Generic;

namespace Legoas_Test.Models
{
    public partial class Layar
    {
        public Layar()
        {
            TLayars = new HashSet<TLayar>();
        }

        public long Id { get; set; }
        public string KodeLayar { get; set; }
        public string NamaLayar { get; set; }

        public virtual ICollection<TLayar> TLayars { get; set; }
    }
}

Legoas_Test/Models/Pengguna.cs
using System;
using System.Collections.Generic;

namespace Legoas_Test.Models
{
    public partial class Pengguna
    {
        public long Id { get; set; }
        public string NamaPengguna { get; set; }
        public string Alamat { get; set; }
        public string KodePos { get; set; }
        public string Provinsi { get; set; }
        public string Kantor { get; set; }
        public long AkunId { get; set; }

        public virtual Akun Akun { get; set; }
    }
}

Legoas_Test/ViewModels/DaftarAkunViewModel.cs
using Legoas_Test.DTOs;
using System.Collections;
using System.Collections.Generic;

namespace Legoas_Test.ViewModels
{
    public class DaftarAkunViewModel
    {
        public IEnumerable<DaftarAkunDTO> DaftarAkun { get; set; }   
    }
}

Legoas_Test/ViewModels/LayarViewModel.cs
using Legoas_Test.Models;
using System.Collections.Generic;

namespace Legoas_Test.ViewModels
{
    public class LayarViewModel
    {
        public int id { get; set; }           

        public IEnumerable<Layar> Layars { get; set; }
    }
}

Legoas_Test/ViewModels/PendaftaranViewModel.cs
using Legoas_Test.DTOs;
using Legoas_Test.Models;
using System.Collections;
using System.Collections.Generic;

namespace Legoas_Test.ViewModels
{
    public class PendaftaranViewModel
    {
        public IEnumerable<Peran> Perans { get; set; }
    }
}

Legoas_Test/ViewModels/PenggunaViewModel.cs
using Legoas_Test.Models;
using System.Collections.Generic;

namespace Legoas_Test.ViewModels
{
    public class PenggunaViewModel
    {
        public int id { get; set; }

        public IEnumerable<Kantor> Kantors { get; set; }
    }
}

Legoas_Test/Controllers/LegoasController.cs
using Legoas_Test.DTOs;
using Legoas_Test.Interfaces;
using Legoas_Test.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Legoas_Test.Controllers
{
    public class LegoasController : Controller
    {

        private readonly ILogger<HomeController> _logger;
        private readonly IPendaftaranProvider _pendaftaranProvider;
        private readonly IDaftarAkunProvider _daftarAkunProvider;

        public LegoasController(ILogger<HomeController> logger, IPendaftaranProvider pendaftaranProvider, IDaftarAkunProvider daftarAkunProvider)
        {
            _logger = logger;
            _pendaftaranProvider = pendaftaranProvider;
            _daftarAkunProvider = daftarAkunProvider;
        }

        // GET: LegoasController
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Pendaftaran()
        {
            var vm = new PendaftaranViewModel
            {              
                Perans = _pendaftaranProvider.GetPeran()
            };

            return View(vm);
        }

        [HttpPost]
        public IActionResult InsertPeran(string namaAkun, string password, int[] perans)
        {
            var checkAkuns = _pendaftaranProvider.CheckIfAkunExists(namaAkun);

            if(!checkAkuns) { return Json(new { id = 0 }); }

            int resultInitial = _pendaftaranProvider.InsertInitialPendaftaran(namaAkun, password, perans);

            return Json(new { id = resultInitial });
        }
        
        [HttpPost]
        public IActionResult Pengguna(int id)
        {
            var vm = new PenggunaViewModel
            {
                id = id,
                Kantors = _pendaftaranProvider.GetKantor()
            };

            return View(vm);  
        }

        [HttpPost]
        public IActionResult InsertPengguna(InsertPenggunaDTO pengguna)
        {
           int resultPengguna = _pendaftaranProvider.InsertPengguna(pengguna);

           return Json(new { id = resultPengguna});
        }

        [HttpPost]
        public IActionResult Layar(int id)
        {
            var vm = new LayarViewModel
            {
                id = id,
                Layars = _pendaftaranProvider.GetLayar()
            };
            return View(vm);
        }

        [HttpPost]
        public IActionResult InsertLayar(int id, int[] layars)
        {
            string result = "Success";

            int resultLayar = _pendaftaranProvider.InsertLayar(id,layars);

            if (resultLayar == 0) result = "Failed"; 

            return Json(new { message = result });
        }

        [HttpGet]
        public IActionResult DaftarAkun()
        {
            var daftarAkun = _daftarAkunProvider.GetPeran();
            var vm = new DaftarAkunViewModel
            {
                DaftarAkun = daftarAkun
            };

            return View(vm);
        }







        //// GET: LegoasController/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        //// GET: LegoasController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: LegoasController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: LegoasController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: LegoasController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: LegoasController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: LegoasController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

Legoas_Test/Views/Legoas/DaftarAkun.cshtml
@model Legoas_Test.ViewModels.DaftarAkunViewModel

<div class="container">
    <input id="input-daftar" type="text" placeholder="Search..">
    <br />
    <table id="table-daftar-1" class="table table-bordered">
        <thead>
            <tr>
                <th>Nama Akun</th>
                <th>Tgl Daftar Akun</th>
                <th>Nama Pengguna</th>
                <th>Peran</th>
            </tr>
        </thead>
        <tbody id="table-daftar-1-body">
            @foreach (var daftar in Model.DaftarAkun)
                {
                   <tr>
                    <td>@daftar.namaAkun</td>
                    <td>@daftar.TglDaftar</td>
                    <td>@daftar.namaPengguna</td>
                    <td>@daftar.peran</td>
                   </tr>
                }         
        </tbody>              
    </table>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#input-daftar").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#table-daftar-1-body tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
</div>

Legoas_Test/Views/Legoas/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div>
    <div class="row">
        <div class="col-md-8">
            <form id="form-pendaftaran" method="get" asp-action="Pendaftaran" asp-controller="Legoas">
                <button id="pendaftaran" type="submit" style="color:blue;">PENDAFTARAN</button>
            </form>
            
        </div>
        <div class="col-md-8">
            <form id="form-daftar" method="get" asp-action="DaftarAkun" asp-controller="Legoas">
                <button id="daftar-akun" type="submit" style="color:dimgrey;">DAFTAR AKUN </button>
            </form>
            
        </div>
    </div>
</div>

@section Scripts{
    <script type="text/javascript">

    </script>
}

Legoas_Test/Views/Legoas/Layar.cshtml
@model Legoas_Test.ViewModels.LayarViewModel


<div class="container">
    <form>
        <div class="form-group">
            <label for="exampleFormControlInput1">Pilih Layar :</label>
            <ul>
                @foreach (var layar in Model.Layars)
                {
                    <li>
                        <input type="checkbox" value="@layar.Id" name="chk-box-3">
                        @layar.NamaLayar
                    </li>
                }
            </ul>
        </div>
    </form>
    <button class="btn btn-primary" type="button" id="test1" onclick="Finish()">SELESAI</button>
    <form id="submit-all" method="get" asp-action="Index" asp-controller="Legoas"></form>

    <script type="text/javascript">
        function Finish (){
            var id = @Model.id;
            var layars = [];

            $('input[name="chk-box-3"]:checked').each(function () {
                layars.push(this.value);
            });

            $.post("@Url.Action("InsertLayar")", { id, layars }, function (res) {
                var msg = res.message
                alert(msg);
                $("#submit-all").submit();
            });
        }
    </script>
</div>

Legoas_Test/Views/Legoas/Pendaftaran.cshtml
@model Legoas_Test.ViewModels.PendaftaranViewModel

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdn.rawgit.com/harvesthq/chosen/gh-pages/chosen.jquery.min.js"></script>
<link href="https://cdn.rawgit.com/harvesthq/chosen/gh-pages/chosen.min.css" rel="stylesheet" />
<div class="container">
    <form>
        <div class="form-group">
            <label for="exampleFormControlInput1">Nama Akun</label>
            <input type="text" class="form-control" id="namaAkun" placeholder="melissa_huang">
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput1">Password</label>
            <input type="password" class="form-control" id="password" >
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput1">Pilih Peran :</label>
            <ul>
                @foreach (var peran in Model.Perans)
                {
                    <li>
                        <input type="checkbox" value="@peran.Id" name="chk-box-1"> 
                        @peran.NamaPeran
                    </li>
                }
            </ul>
        </div>
        @*<div class="form-group">
            <select data-placeholder="Begin typing a name to filter..." multiple class="chosen-select" name="test">
                @foreach (var kantor in Model.Kantors)
                {
                    <option value="@kantor.Id">
                        @kantor.NamaCabang
                    </option>
                }
            </select>
        </div>
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Example textarea</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
        </div>*@
    </form>

    <form id="form-pengguna" method="post" asp-action="Pengguna" asp-controller="Legoas">
        <input type="hidden" id="id-akun" name="id">
    </form>
    <button class="btn btn-primary" type="button" id="test1" onclick="Next1()">NEXT</button>

    <script type="text/javascript">
        //$(".chosen-select").chosen({
        //    no_results_text: "Oops, nothing found!"
        //})

        function Next1 () {
            var namaAkun = $("#namaAkun").val();
            var password = $("#password").val();
            var perans = [];

            $('input[name="chk-box-1"]:checked').each(function () {
                perans.push(this.value);                
            });

            $.post("@Url.Action("InsertPeran")",{ namaAkun, password, perans }, function(res){
                var id = res.id
                if(id == 0){
                    alert("Nama Akun Sudah Terdaftar: Silahkan pilih nama akun lain");
                }
                else{
                    alert(id);
                    $("#id-akun").val(id);
                    alert($("#id-akun").val());
                    $("#form-pengguna").submit();
                }                
            });
        }
        

        //$(".chosen-select").chosen().change(function () {
        //    var myValues = $('#my-select').chosen().val();

        //    alert(myValues);
        //});
    </script>
</div>

Legoas_Test/Views/Legoas/Pengguna.cshtml
@model Legoas_Test.ViewModels.PenggunaViewModel

<div class="container">
    <h4>Silahkan Lengkapi Data Pengguna Berikut (Tidak Wajib)</h4>
    <form>
        <div class="form-group">
            <label for="namaPengguna">Nama Pengguna</label>
            <input type="text" class="form-control" id="namaPengguna" placeholder="Isi dengan nama lengkap">
        </div>
        <div class="form-group">
            <label for="alamat">Alamat</label>
            <input type="text" class="form-control" id="alamat">
        </div>
        <div class="form-group">
            <label for="kodePos">Kode Pos</label>
            <input type="text" class="form-control" id="kodePos" >
        </div>
        <div class="form-group">
            <label for="provinsi">Provinsi</label>
            <input type="text" class="form-control" id="provinsi">
        </div>
        <div class="form-group">
            <label for="exampleFormControlInput1">Pilih Kantor :</label>
            <ul>
                @foreach (var kantor in Model.Kantors)
                {
                    <li>
                        <input type="checkbox" value="@kantor.Id" name="chk-box-2">
                        @kantor.NamaCabang
                    </li>
                }
            </ul>
        </div>  
    </form>
    <form id="form-layar" method="post" asp-action="Layar" asp-controller="Legoas">
        <input type="hidden" id="id-akun-2" name="id">
    </form>

    <p>tidak wajib melengkapi data pengguna, apabila ingin lagsung melanjutkan silahkan klik NEXT</p>
    <button class="btn btn-primary" type="button" id="test1" onclick="Next2()">NEXT</button>

    <script type="text/javascript">

        function Next2() {
            var namaPengguna = $("#namaPengguna").val();
            var alamat = $("#alamat").val();
            var kodePos = $("#kodePos").val();
            var provinsi = $("#provinsi").val();
            var kantors = [];
            var akunId = @Model.id;

            $('input[name="chk-box-2"]:checked').each(function () {
                kantors.push(this.value);
            });

            $.post("@Url.Action("InsertPengguna")", { namaPengguna, alamat, kodePos, provinsi, kantors, akunId }, function (res) {
                var id = res.id
                alert(id); 
                $("#id-akun-2").val(id);
                $("#form-layar").submit();
            });
        }
    
    </script>
</div>